basic:
    name: 'www.opploans.com batch 9'
    environments:
        production: 'https://www.opploans.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /faqs/what-website-can-i-use-to-enter-my-promo-code
        - /faqs/i-received-an-opploans-mail-offer-intended-for-another-person-how-can-i-stop-receiving-these-letters
        - /faqs/i-would-like-to-opt-out-of-receiving-mail-offers
        - /faqs/how-do-i-avoid-smishing-scams
        - /faqs/are-opploans-products-available-in-every-state
        - /faqs/what-is-an-apr
        - /faqs/can-my-personal-information-get-deleted
        - /faqs/what-do-i-do-if-im-a-victim-of-identity-theft-or-fraud
        - /faqs/who-are-your-lending-partners
        - /faqs/is-opploans-a-scam
    monitoring:
        days: {  }
        type: daily
        schedule_time: '09:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
